-- Step 001: SECURITYADMIN tasks (roles, users, RSA keys).

-- =====================
-- DEV
-- =====================


CREATE ROLE IF NOT EXISTS ROLE_KAFKA_DEV;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_DEV
  LOGIN_NAME = 'KAFKA_CONNECT_DEV'
  DISPLAY_NAME = 'Kafka Connect DEV'
  DEFAULT_ROLE = ROLE_KAFKA_DEV
  DEFAULT_WAREHOUSE = WH_DEV
  DEFAULT_NAMESPACE = BOOKIBET_DEV.RAW
  MUST_CHANGE_PASSWORD = FALSE;

-- Replace with the actual public key for KAFKA_CONNECT_DEV.
ALTER USER KAFKA_CONNECT_DEV
  SET RSA_PUBLIC_KEY_2='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYDhcsxUP2H4UzZDyR0lT22jCnaLtQ5BI0i6hsHGP2vuGhNOoOUquKsRDhs1J8+2P/UkBbETYY0XY/j7q5BUdAFl/eAn79kEIMbmjH3rh8nkq+4+czqI5gAZSZRK1d79KO3Lkxygii36dEq9QeyeO7NhZTHiVX1HJi3dlDkAFdi+kg+zzWvFNstEzj0ry+FmjP0K9yNiif2ZNv5mX2S53PEQSYSSApp0b3T5azf150cBEeUqu9D4bvdjRKZ2Lt3aKAc6cp67FhKA/e+BfUTvDedk7ODpAHLPPrqnee6Lm8w48lugHecKNgWmUcOmOargjswshagyi3TAinGGmhT/NwIDAQAB';

GRANT ROLE ROLE_KAFKA_DEV TO USER KAFKA_CONNECT_DEV;

-- =====================
-- STAGING
-- =====================


CREATE ROLE IF NOT EXISTS KAFKA_CONNECT_ROLE_STAGING;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_STAGING
  LOGIN_NAME = 'KAFKA_CONNECT_STAGING'
  DISPLAY_NAME = 'Kafka Connect STAGING'
  DEFAULT_ROLE = KAFKA_CONNECT_ROLE_STAGING
  DEFAULT_WAREHOUSE = WH_INGEST_STAGING
  DEFAULT_NAMESPACE = BOOKIBET_STAGING.RAW
  MUST_CHANGE_PASSWORD = FALSE;

-- Replace with the actual public key for KAFKA_CONNECT_STAGING.
ALTER USER KAFKA_CONNECT_STAGING
  SET RSA_PUBLIC_KEY_2='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYDhcsxUP2H4UzZDyR0lT22jCnaLtQ5BI0i6hsHGP2vuGhNOoOUquKsRDhs1J8+2P/UkBbETYY0XY/j7q5BUdAFl/eAn79kEIMbmjH3rh8nkq+4+czqI5gAZSZRK1d79KO3Lkxygii36dEq9QeyeO7NhZTHiVX1HJi3dlDkAFdi+kg+zzWvFNstEzj0ry+FmjP0K9yNiif2ZNv5mX2S53PEQSYSSApp0b3T5azf150cBEeUqu9D4bvdjRKZ2Lt3aKAc6cp67FhKA/e+BfUTvDedk7ODpAHLPPrqnee6Lm8w48lugHecKNgWmUcOmOargjswshagyi3TAinGGmhT/NwIDAQAB';

GRANT ROLE KAFKA_CONNECT_ROLE_STAGING TO USER KAFKA_CONNECT_STAGING;

-- =====================
-- PROD
-- =====================


CREATE ROLE IF NOT EXISTS KAFKA_CONNECT_ROLE_PROD;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_PROD
  LOGIN_NAME = 'KAFKA_CONNECT_PROD'
  DISPLAY_NAME = 'Kafka Connect PROD'
  DEFAULT_ROLE = KAFKA_CONNECT_ROLE_PROD
  DEFAULT_WAREHOUSE = WH_INGEST_PROD
  DEFAULT_NAMESPACE = BOOKIBET_PROD.RAW
  MUST_CHANGE_PASSWORD = FALSE;

-- Replace with the actual public key for KAFKA_CONNECT_PROD.
ALTER USER KAFKA_CONNECT_PROD
  SET RSA_PUBLIC_KEY_2='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYDhcsxUP2H4UzZDyR0lT22jCnaLtQ5BI0i6hsHGP2vuGhNOoOUquKsRDhs1J8+2P/UkBbETYY0XY/j7q5BUdAFl/eAn79kEIMbmjH3rh8nkq+4+czqI5gAZSZRK1d79KO3Lkxygii36dEq9QeyeO7NhZTHiVX1HJi3dlDkAFdi+kg+zzWvFNstEzj0ry+FmjP0K9yNiif2ZNv5mX2S53PEQSYSSApp0b3T5azf150cBEeUqu9D4bvdjRKZ2Lt3aKAc6cp67FhKA/e+BfUTvDedk7ODpAHLPPrqnee6Lm8w48lugHecKNgWmUcOmOargjswshagyi3TAinGGmhT/NwIDAQAB';

GRANT ROLE KAFKA_CONNECT_ROLE_PROD TO USER KAFKA_CONNECT_PROD;
