-- Step 002: SYSADMIN tasks (DB/schema/warehouse + grants).

-- =====================
-- DEV
-- =====================


CREATE DATABASE IF NOT EXISTS BOOKIBET_DEV;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_DEV.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_DEV TO ROLE ROLE_KAFKA_DEV;
GRANT USAGE ON DATABASE BOOKIBET_DEV TO ROLE ROLE_KAFKA_DEV;
GRANT USAGE ON SCHEMA BOOKIBET_DEV.RAW TO ROLE ROLE_KAFKA_DEV;
GRANT CREATE TABLE ON SCHEMA BOOKIBET_DEV.RAW TO ROLE ROLE_KAFKA_DEV;
GRANT CREATE STAGE ON SCHEMA BOOKIBET_DEV.RAW TO ROLE ROLE_KAFKA_DEV;
GRANT CREATE PIPE ON SCHEMA BOOKIBET_DEV.RAW TO ROLE ROLE_KAFKA_DEV;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA BOOKIBET_DEV.RAW TO ROLE ROLE_KAFKA_DEV;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA BOOKIBET_DEV.RAW TO ROLE ROLE_KAFKA_DEV;

-- =====================
-- STAGING
-- =====================


CREATE DATABASE IF NOT EXISTS BOOKIBET_STAGING;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_STAGING.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_STAGING
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_INGEST_STAGING TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT USAGE ON DATABASE BOOKIBET_STAGING TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT USAGE ON SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT CREATE TABLE ON SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT CREATE STAGE ON SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT CREATE PIPE ON SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;

-- =====================
-- PROD
-- =====================


CREATE DATABASE IF NOT EXISTS BOOKIBET_PROD;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_PROD.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_PROD
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_INGEST_PROD TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT USAGE ON DATABASE BOOKIBET_PROD TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT USAGE ON SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT CREATE TABLE ON SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT CREATE STAGE ON SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT CREATE PIPE ON SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
