-- Snowflake setup for Kafka Connect (staging + prod).
-- Run with SECURITYADMIN for roles/users, SYSADMIN for DB/warehouse.

-- =====================
-- STAGING
-- =====================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS KAFKA_CONNECT_ROLE_STAGING;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_STAGING
  LOGIN_NAME = 'KAFKA_CONNECT_STAGING'
  DISPLAY_NAME = 'Kafka Connect STAGING'
  DEFAULT_ROLE = KAFKA_CONNECT_ROLE_STAGING
  DEFAULT_WAREHOUSE = WH_INGEST_STAGING
  DEFAULT_NAMESPACE = BOOKIBET_STAGING.RAW
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE KAFKA_CONNECT_ROLE_STAGING TO USER KAFKA_CONNECT_STAGING;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS BOOKIBET_STAGING;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_STAGING.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_STAGING
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_INGEST_STAGING TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT USAGE ON DATABASE BOOKIBET_STAGING TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT USAGE, CREATE TABLE, INSERT, SELECT ON SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;

-- =====================
-- PROD
-- =====================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS KAFKA_CONNECT_ROLE_PROD;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_PROD
  LOGIN_NAME = 'KAFKA_CONNECT_PROD'
  DISPLAY_NAME = 'Kafka Connect PROD'
  DEFAULT_ROLE = KAFKA_CONNECT_ROLE_PROD
  DEFAULT_WAREHOUSE = WH_INGEST_PROD
  DEFAULT_NAMESPACE = BOOKIBET_PROD.RAW
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE KAFKA_CONNECT_ROLE_PROD TO USER KAFKA_CONNECT_PROD;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS BOOKIBET_PROD;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_PROD.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_PROD
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_INGEST_PROD TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT USAGE ON DATABASE BOOKIBET_PROD TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT USAGE, CREATE TABLE, INSERT, SELECT ON SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
