-- Snowflake init for Kafka Connect (dev/staging/prod).
-- Run with SECURITYADMIN for roles/users, SYSADMIN for DB/warehouse.

-- =====================
-- DEV
-- =====================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_KAFKA_DEV;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_DEV
  LOGIN_NAME = 'KAFKA_CONNECT_DEV'
  DISPLAY_NAME = 'Kafka Connect DEV'
  DEFAULT_ROLE = ROLE_KAFKA_DEV
  DEFAULT_WAREHOUSE = WH_DEV
  DEFAULT_NAMESPACE = BOOKIBET_DEV.RAW
  MUST_CHANGE_PASSWORD = FALSE;

-- Replace with the actual public key for KAFKA_CONNECT_DEV.
ALTER USER KAFKA_CONNECT_DEV
  SET RSA_PUBLIC_KEY_2='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYDhcsxUP2H4UzZDyR0lT22jCnaLtQ5BI0i6hsHGP2vuGhNOoOUquKsRDhs1J8+2P/UkBbETYY0XY/j7q5BUdAFl/eAn79kEIMbmjH3rh8nkq+4+czqI5gAZSZRK1d79KO3Lkxygii36dEq9QeyeO7NhZTHiVX1HJi3dlDkAFdi+kg+zzWvFNstEzj0ry+FmjP0K9yNiif2ZNv5mX2S53PEQSYSSApp0b3T5azf150cBEeUqu9D4bvdjRKZ2Lt3aKAc6cp67FhKA/e+BfUTvDedk7ODpAHLPPrqnee6Lm8w48lugHecKNgWmUcOmOargjswshagyi3TAinGGmhT/NwIDAQAB';

GRANT ROLE ROLE_KAFKA_DEV TO USER KAFKA_CONNECT_DEV;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS BOOKIBET_DEV;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_DEV.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_DEV
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_DEV TO ROLE ROLE_KAFKA_DEV;
GRANT USAGE ON DATABASE BOOKIBET_DEV TO ROLE ROLE_KAFKA_DEV;
GRANT USAGE, CREATE TABLE, INSERT, SELECT ON SCHEMA BOOKIBET_DEV.RAW TO ROLE ROLE_KAFKA_DEV;

-- =====================
-- STAGING
-- =====================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS KAFKA_CONNECT_ROLE_STAGING;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_STAGING
  LOGIN_NAME = 'KAFKA_CONNECT_STAGING'
  DISPLAY_NAME = 'Kafka Connect STAGING'
  DEFAULT_ROLE = KAFKA_CONNECT_ROLE_STAGING
  DEFAULT_WAREHOUSE = WH_INGEST_STAGING
  DEFAULT_NAMESPACE = BOOKIBET_STAGING.RAW
  MUST_CHANGE_PASSWORD = FALSE;

-- Replace with the actual public key for KAFKA_CONNECT_STAGING.
ALTER USER KAFKA_CONNECT_STAGING
  SET RSA_PUBLIC_KEY_2='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYDhcsxUP2H4UzZDyR0lT22jCnaLtQ5BI0i6hsHGP2vuGhNOoOUquKsRDhs1J8+2P/UkBbETYY0XY/j7q5BUdAFl/eAn79kEIMbmjH3rh8nkq+4+czqI5gAZSZRK1d79KO3Lkxygii36dEq9QeyeO7NhZTHiVX1HJi3dlDkAFdi+kg+zzWvFNstEzj0ry+FmjP0K9yNiif2ZNv5mX2S53PEQSYSSApp0b3T5azf150cBEeUqu9D4bvdjRKZ2Lt3aKAc6cp67FhKA/e+BfUTvDedk7ODpAHLPPrqnee6Lm8w48lugHecKNgWmUcOmOargjswshagyi3TAinGGmhT/NwIDAQAB';

GRANT ROLE KAFKA_CONNECT_ROLE_STAGING TO USER KAFKA_CONNECT_STAGING;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS BOOKIBET_STAGING;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_STAGING.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_STAGING
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_INGEST_STAGING TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT USAGE ON DATABASE BOOKIBET_STAGING TO ROLE KAFKA_CONNECT_ROLE_STAGING;
GRANT USAGE, CREATE TABLE, INSERT, SELECT ON SCHEMA BOOKIBET_STAGING.RAW TO ROLE KAFKA_CONNECT_ROLE_STAGING;

-- =====================
-- PROD
-- =====================
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS KAFKA_CONNECT_ROLE_PROD;
CREATE USER IF NOT EXISTS KAFKA_CONNECT_PROD
  LOGIN_NAME = 'KAFKA_CONNECT_PROD'
  DISPLAY_NAME = 'Kafka Connect PROD'
  DEFAULT_ROLE = KAFKA_CONNECT_ROLE_PROD
  DEFAULT_WAREHOUSE = WH_INGEST_PROD
  DEFAULT_NAMESPACE = BOOKIBET_PROD.RAW
  MUST_CHANGE_PASSWORD = FALSE;

-- Replace with the actual public key for KAFKA_CONNECT_PROD.
ALTER USER KAFKA_CONNECT_PROD
  SET RSA_PUBLIC_KEY_2='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYDhcsxUP2H4UzZDyR0lT22jCnaLtQ5BI0i6hsHGP2vuGhNOoOUquKsRDhs1J8+2P/UkBbETYY0XY/j7q5BUdAFl/eAn79kEIMbmjH3rh8nkq+4+czqI5gAZSZRK1d79KO3Lkxygii36dEq9QeyeO7NhZTHiVX1HJi3dlDkAFdi+kg+zzWvFNstEzj0ry+FmjP0K9yNiif2ZNv5mX2S53PEQSYSSApp0b3T5azf150cBEeUqu9D4bvdjRKZ2Lt3aKAc6cp67FhKA/e+BfUTvDedk7ODpAHLPPrqnee6Lm8w48lugHecKNgWmUcOmOargjswshagyi3TAinGGmhT/NwIDAQAB';

GRANT ROLE KAFKA_CONNECT_ROLE_PROD TO USER KAFKA_CONNECT_PROD;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS BOOKIBET_PROD;
CREATE SCHEMA IF NOT EXISTS BOOKIBET_PROD.RAW;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_PROD
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE WH_INGEST_PROD TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT USAGE ON DATABASE BOOKIBET_PROD TO ROLE KAFKA_CONNECT_ROLE_PROD;
GRANT USAGE, CREATE TABLE, INSERT, SELECT ON SCHEMA BOOKIBET_PROD.RAW TO ROLE KAFKA_CONNECT_ROLE_PROD;
