apiVersion: v1
kind: Secret
metadata:
  name: neuroplastiq-secrets
  namespace: neuroplastiq
type: Opaque
stringData:
  NEURO_REGISTRY_DB: "neuro_registry"
  NEURO_REGISTRY_USER: "neuro_registry"
  NEURO_REGISTRY_PASSWORD: "57[^*c0GE3a7nP3v6-a"
  NEURO_REGISTRY_HOST: "neuro-staging-neuro-registry.cn2k04asgnmd.ap-southeast-2.rds.amazonaws.com"
  NEURO_REGISTRY_PORT: "5432"
  TOKEN_URL: "https://bos-apollo.auth.ap-southeast-2.amazoncognito.com/oauth2/token"
  CLIENT_ID: "56bc4u6ia8gd6ilvasmbceares"
  CLIENT_SECRET: "jerjps5rjm65301lgarh6u5212mg2vqljaufj8o3ojljiavu70d"
  PONYBET_X_API_KEY: "56bc4u6ia8gd6ilvasmbceares"
  RACING_PONYBET_X_API_KEY: "1va9olufe5nbf1r704durfkfa5"
  BETIT_X_API_KEY: "7m70ns60lc6g3ovhhdjhs0lcb6"
  EARLYCROW_X_API_KEY: "stj6tnonpdmro0p4jnl4sqdu2"
  KNUCKLEBET_X_API_KEY: "5mqoe8m1veq72bl5ds0napssho"
  BOS_GQL_X_API_KEY: "56bc4u6ia8gd6ilvasmbceares"
