---
apiVersion: iam.amazonaws.com/v1alpha5
kind: IAMServiceAccount
metadata:
  name: kafka-broker
  namespace: confluent
spec:
  awsRegion: ap-southeast-2
  roleName: kafka-broker-role
  attachPolicy:
    Version: "2012-10-17"
    Statement:
      - Effect: Allow
        Action:
          - "ec2:DescribeInstances"
          - "ec2:DescribeSecurityGroups"
          - "ec2:DescribeVolumes"
          - "ec2:CreateTags"
        Resource: "*"
