---
namespace: confluent

kraftController:
  nodeId: 3000
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload.bookibet.io/pool
                  operator: In
                  values:
                    - confluent
    tolerations:
      - key: dedicated
        operator: Equal
        value: confluent
        effect: NoSchedule
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

kafka:
  replicas: 3
  oneReplicaPerNode: true
  storageSize: "50Gi"
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload.bookibet.io/pool
                  operator: In
                  values:
                    - confluent
    tolerations:
      - key: dedicated
        operator: Equal
        value: confluent
        effect: NoSchedule
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
  config:
    num.partitions: 3
    default.replication.factor: 3
    min.insync.replicas: 2
    auto.create.topics.enable: true
    offsets.topic.replication.factor: 3
    transaction.state.log.replication.factor: 3
    transaction.state.log.min.isr: 2
    confluent.license.topic.replication.factor: 3
    confluent.metadata.topic.replication.factor: 3
    confluent.metrics.reporter.topic.replicas: 3
    confluent.cluster.link.enable: false
    confluent.balancer.enable: false

connect:
  replicas: 1
  offsetStorageReplicationFactor: 3
  configStorageReplicationFactor: 3
  statusStorageReplicationFactor: 3
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload.bookibet.io/pool
                  operator: In
                  values:
                    - confluent
    tolerations:
      - key: dedicated
        operator: Equal
        value: confluent
        effect: NoSchedule
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1
        memory: 3Gi

schemaRegistry:
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload.bookibet.io/pool
                  operator: In
                  values:
                    - confluent
    tolerations:
      - key: dedicated
        operator: Equal
        value: confluent
        effect: NoSchedule
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

kafkaRestProxy:
  enabled: true
  replicas: 1
  podTemplate:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload.bookibet.io/pool
                  operator: In
                  values:
                    - confluent
    tolerations:
      - key: dedicated
        operator: Equal
        value: confluent
        effect: NoSchedule
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  configOverrides:
    server:
      - value.subject.name.strategy=io.confluent.kafka.serializers.subject.RecordNameStrategy
      - key.subject.name.strategy=io.confluent.kafka.serializers.subject.RecordNameStrategy
      - producer.value.subject.name.strategy=io.confluent.kafka.serializers.subject.RecordNameStrategy
      - producer.key.subject.name.strategy=io.confluent.kafka.serializers.subject.RecordNameStrategy
